name: JavaCI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn -B package --file pom.xml
    - name: Copy jar
      run: cp target/DevopsSpring-0.0.1-SNAPSHOT.jar ~/www/spring02/DevopsSpring-0.0.1-SNAPSHOT.jar
    - name: restart
      run: sudo systemctl restart spring02